Repository ISISComputingGroup/EPICS-MercuryiTC, pull requests merged in 2020-06, with the labels that each got.

#7 Ticket1392 mercury epics ioc
  MercuryiTCApp/Db/MercuryGlobal.db
  MercuryiTCApp/Db/MercuryLevel.db
  MercuryiTCApp/Db/MercuryPressure.db
  MercuryiTCApp/Db/MercuryTemp.db
  MercuryiTCApp/protocol/Makefile
  MercuryiTCApp/protocol/lv_MercuryLevel.xml
  MercuryiTCApp/protocol/lv_MercuryPressure.xml
  MercuryiTCApp/protocol/lv_MercuryTemp.xml
  MercuryiTCApp/protocol/mercuryitc.proto
  MercuryiTCApp/src/build.mak
  MercuryiTCApp/src/parse_catalog.c
  MercuryiTCApp/src/parse_catalog.dbd
  configure/RELEASE
  iocBoot/iocMercuryiTC/st-common.cmd
  iocBoot/iocMercuryiTC/st-level.cmd
  iocBoot/iocMercuryiTC/st-pressure.cmd
  iocBoot/iocMercuryiTC/st-temp.cmd
Labels: size/XXL

#8 Update units on mecruty itc
  MercuryiTCApp/Db/MercuryPressure.db
Labels: size/XS

#9 Fix compile error
  MercuryiTCApp/src/parse_catalog.c
Labels: size/M
