Repository ISISComputingGroup/EPICS-MercuryiTC, pull requests merged in 2020-10, with the labels that each got.

#11 Ticket5546 little blue cryostat
  MercuryiTCApp/Db/Makefile
  MercuryiTCApp/Db/MercuryPressure.db
  MercuryiTCApp/Db/MercurySPC.db
  MercuryiTCApp/Db/MercurySPCAvailable.db
  MercuryiTCApp/src/build.mak
  MercuryiTCApp/src/full_auto.c
  MercuryiTCApp/src/full_auto.dbd
  MercuryiTCApp/src/user1DTableSub.c
  configure/RELEASE
  iocBoot/iocMercuryiTC/st-common.cmd
  iocBoot/iocMercuryiTC/st-level.cmd
  iocBoot/iocMercuryiTC/st-pressure.cmd
  iocBoot/iocMercuryiTC/st-temp-spc.cmd
  iocBoot/iocMercuryiTC/st-temp.cmd
Labels: size/XL

#12 Name not just prec
  MercuryiTCApp/src/full_auto.c
Labels: size/XS

#13 Move int to top of declaration
  MercuryiTCApp/src/user1DTableSub.c
Labels: size/XS

#14 add misssing not for available flag
  MercuryiTCApp/Db/MercurySPCAvailable.db
  iocBoot/iocMercuryiTC/st-temp-spc.cmd
Labels: size/XS

#15 Remove old IOC and fix build logic
  MercuryiTCApp/src/Makefile
  MercuryiTCApp/src/MercuryiTCMain.cpp
  MercuryiTCApp/src/build.mak
  configure/RELEASE
  iocBoot/Makefile
  iocBoot/iocMercuryiTC/Makefile
  iocBoot/iocMercuryiTC/config.xml
  iocBoot/iocMercuryiTC/st-common.cmd
  iocBoot/iocMercuryiTC/st-level.cmd
  iocBoot/iocMercuryiTC/st-pressure.cmd
  iocBoot/iocMercuryiTC/st-temp-spc.cmd
  iocBoot/iocMercuryiTC/st-temp.cmd
  iocBoot/iocMercuryiTC/st.cmd
Labels: size/L

#16 Add cryostat config
  settings/little_blue_cryostat.txt
Labels: size/S
